export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  EXTENSION_BLOCKED: 'EXTENSION_BLOCKED',
  NAME_TOO_LONG: 'NAME_TOO_LONG',

  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',

  SHARE_LINK_EXPIRED: 'SHARE_LINK_EXPIRED',
  SHARE_LINK_INVALID_PASSWORD: 'SHARE_LINK_INVALID_PASSWORD',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
